# Generated by Django 5.0.4 on 2024-04-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
