# Generated by Django 5.0.4 on 2024-04-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_data_name_data_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='audio',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(max_length=50, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=50, null=True, verbose_name='Вопрос'),
        ),
    ]
