# Generated by Django 5.0.4 on 2024-04-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questions_answerwrong1_questions_answerwrong2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answerwrong1',
            field=models.TextField(max_length=255, null=True, verbose_name='Неправильный ответ 1'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answerwrong2',
            field=models.TextField(max_length=255, null=True, verbose_name='Неправильный ответ 2'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
    ]
