# Generated by Django 4.2.4 on 2024-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_questions_answer_alter_questions_answerwrong1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='images',
            field=models.FileField(null=True, upload_to='files_to/images/'),
        ),
    ]
