# Generated by Django 4.2.4 on 2024-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_images_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(null=True, upload_to='files_to/images/'),
        ),
    ]
