# Generated by Django 5.0.4 on 2024-04-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_questions_audio_questions_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answerwrong1',
            field=models.TextField(max_length=50, null=True, verbose_name='Неправильный ответ 1'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answerwrong2',
            field=models.TextField(max_length=50, null=True, verbose_name='Неправильный ответ 2'),
        ),
    ]
